### ISSUE TITLE
Invalid Syntax on powernoise.py

### ISSUE THREAD

**Issue by claychinasky** [blepping/ComfyUI-sonar#7]
I'm getting this error after last update, using python 3.10,
```
Traceback (most recent call last):
  File "/mnt/1st/ai_apps/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/1st/ai_apps/ComfyUI/custom_nodes/ComfyUI-sonar/__init__.py", line 1, in <module>
    from .py import freeu_extreme, nodes, powernoise, sonar
  File "/mnt/1st/ai_apps/ComfyUI/custom_nodes/ComfyUI-sonar/py/freeu_extreme.py", line 6, in <module>
    from .powernoise import PowerFilter
  File "/mnt/1st/ai_apps/ComfyUI/custom_nodes/ComfyUI-sonar/py/powernoise.py", line 73
    channel_mixer[*torch.tril_indices(c, c, offset=-1)] = channel_correlation
                  ^
SyntaxError: invalid syntax
```

**Comment by blepping** [comment]
sorry about that, i'm looking into it. i guess that is using a feature Python 3.10 doesn't support.
